version : "3"
services:
  indiatalks-dev-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: indiatalks-dev-app
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "3000:3000"
    networks:
      indiatalks-dev-app-network:
        ipv4_address: 220.30.1.1

# Local network for services running using this docker-compose config
networks:
  indiatalks-dev-app-network:
    ipam:
      driver: default
      config:
        - subnet: 220.30.0.0/16
