# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: git config advice.addIgnoredFile false
    - run: git add dist -f
    - run: git config user.email "jdecode@gmail.com"
    - run: git config user.username "jdecode"
    - run: git config user.name "Jagdeep Singh"
    - run: git commit -m "Build"
    - run: git push -f https://jdecode:${{ secrets.INDIA_TALKS_DEV_PAGES_DEPLOY_TOKEN }}@github.com/indiatalks-dev/indiatalks-dev.git main:gh-pages
